apiVersion: v1
kind: Secret
metadata:
  name: docker.uberresearch.com
  namespace: default
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJkb2NrZXIudWJlcnJlc2VhcmNoLmNvbSI6IHsKCQkJImF1dGgiOiAiY21Ga2RVQjFZbVZ5Y21WelpXRnlZMmd1WTI5dE9pRnViMnRwWVRFeiIKCQl9Cgl9Cn0K
type: kubernetes.io/dockerconfigjson

