apiVersion: v1
kind: Service
metadata:
  name: modules-service
  labels:
    run: modules-service
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 6543
    protocol: TCP
    name: http
  selector:
    run: modules
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: modules
  namespace: default
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: modules
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
      containers:
      - name: modules
        image: docker.uberresearch.com/radar:release_3_23_2_20190328_114800
        ports:
        - containerPort: 6543
        imagePullPolicy: Always
        env:
        - name: INI
          value: "modules_variants_integration"
        - name: API_SERVICE
          value: "false"
        - name: UBER_MODULES
          value: "true"
        - name: MYCATEGORIES_SERVICE
          value: "false"
      imagePullSecrets:
      - name: docker.uberresearch.com
