apiVersion: v1
kind: Service
metadata:
  name: modules-service
  labels:
    run: modules-service
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 6543
    protocol: TCP
    name: http
  selector:
    run: modules
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: modules
  namespace: default
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: modules
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
      containers:
      - name: modules
        image: docker.uberresearch.com/radar:release_3_24_0_20190417_151700
        ports:
        - containerPort: 6543
        imagePullPolicy: Always
        env:
        - name: INI
          value: "modules_variants_integration"
        - name: API_SERVICE
          value: "false"
        - name: UBER_MODULES
          value: "true"
        - name: MYCATEGORIES_SERVICE
          value: "false"
        - name: SQLALCHEMY_URL
          value: "postgresql://admin:admin1234@pg-service/app_usermanagement"
      imagePullSecrets:
      - name: docker.uberresearch.com
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  labels:
    run: webapp-service
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 6543
    protocol: TCP
    name: http
  selector:
    run: webapp
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webapp
  namespace: default
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: webapp
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
      containers:
      - name: webapp
        image: docker.uberresearch.com/radar:release_3_24_0_20190417_151700
        ports:
        - containerPort: 6543
        imagePullPolicy: Always
        env:
        - name: INI
          value: "radar_variants_integration"
        - name: API_SERVICE
          value: "false"
        - name: UBER_MODULES
          value: "true"
        - name: SQLALCHEMY_URL
          value: "postgresql://admin:admin1234@pg-service/app_usermanagement"
        - name: STAMP
          value: "true"
        - name: MIGRATION
          value: "head"
      imagePullSecrets:
      - name: docker.uberresearch.com
