apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-ingress
spec:
  rules:
  - host: integration-k3s.dimensions.ai
    http:
      paths:
      - path: /
        backend:
          serviceName: webapp-service
          servicePort: 80
  - host: integration-k3s.dimensions.ai
    http:
      paths:
      - path: /modules
        backend:
          serviceName: modules-service
          servicePort: 80
